name: Deploy to VPS

on:
  push:
    branches: [ main, telegram-integration ]  # اضافه کردن branch جدید
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Navigate to project directory
          cd /var/www/namayeshakhsiat
          
          # Get current branch
          CURRENT_BRANCH=$(git branch --show-current)
          
          # Pull latest changes from current branch
          git pull origin $CURRENT_BRANCH
          
          # Stop current containers
          docker-compose down
          
          # Rebuild and start containers
          docker-compose up -d --build
          
          # Check if containers are running
          docker ps
          
          # Show logs for debugging
          docker-compose logs --tail=20 backend
          docker-compose logs --tail=20 frontend
